#!/usr/bin/env php
<?php

require __DIR__."/../bootstrap.php";

$app = (new class {
    use Orchestra\Testbench\Traits\CreatesApplication;
    use \Tests\Concerns\SetUpEnvironment;
})->createApplication();

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
